enable-magisk-update = true
parallel-jobs = 1
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
excluded-patches = "'Custom branding' 'Change header' 'Announcements' 'Enable debugging'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/system_neutral1_900 -OlightThemeBackgroundColor=@android:color/system_neutral1_50"
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm-v7a"
build-mode = "both"
excluded-patches = "'Custom branding' 'Change header' 'Announcements' 'Enable debugging'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/system_neutral1_900 -OlightThemeBackgroundColor=@android:color/system_neutral1_50"
